# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 227)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.login_btn.setGeometry(QtCore.QRect(310, 120, 51, 21))
        self.login_btn.setObjectName("login_btn")
        self.account_le = QtWidgets.QLineEdit(self.centralwidget)
        self.account_le.setGeometry(QtCore.QRect(310, 60, 151, 20))
        self.account_le.setText("")
        self.account_le.setPlaceholderText("")
        self.account_le.setObjectName("account_le")
        self.password_le = QtWidgets.QLineEdit(self.centralwidget)
        self.password_le.setGeometry(QtCore.QRect(310, 90, 151, 20))
        self.password_le.setText("")
        self.password_le.setPlaceholderText("")
        self.password_le.setObjectName("password_le")
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setGeometry(QtCore.QRect(410, 120, 51, 21))
        self.cancel_btn.setObjectName("Cancel_btn")
        self.camera_btn = QtWidgets.QPushButton(self.centralwidget)
        self.camera_btn.setGeometry(QtCore.QRect(80, 60, 111, 81))
        self.camera_btn.setObjectName("Camera_btn")
        self.account_lb = QtWidgets.QLabel(self.centralwidget)
        self.account_lb.setGeometry(QtCore.QRect(220, 60, 71, 20))
        self.account_lb.setObjectName("account_lb")
        self.password_lb = QtWidgets.QLabel(self.centralwidget)
        self.password_lb.setGeometry(QtCore.QRect(220, 90, 71, 20))
        self.password_lb.setObjectName("password_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.login_btn.clicked.connect(self.word_get)
        self.cancel_btn.clicked.connect(MainWindow.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.camera_btn.setText(_translate("MainWindow", "Login By Camera"))
        self.account_lb.setText(_translate("MainWindow", "Account"))
        self.password_lb.setText(_translate("MainWindow", "Password"))
